### ISSUE TITLE
DISCORD NICKNAMES

### ISSUE THREAD

**Issue by Reisbrot** [kyranet/Skyra-i18n#8]
If u mention someone in a Bot--Command, the bot should also appreciate thatone. If there is more than one user with tha same Nickname (Is that even possible by Discord?), than u make a list with numbers and stuff the same way as when  u trigger the autocompletion

**Comment by kyranet** [comment]
Mentioning somebody generates a tag like `<@208884658656509953>` or `<@!208884658656509953>` (depending if the member has a nickname), that's already accepted by [the framework](https://github.com/dirigeants/klasa/blob/a4bc98ef022faa16ab78392cb281ddd3ae321163/src/lib/parsers/Resolver.js#L45). Discord tags (`Reisbrot#1019` for example) are also fully supported and unique (there's only one user with the same username and discriminator number). As well as the autocompletion feature accepts **usernames** as they're more objective and less prone to changes compared to nicknames. That's why I did it like that first.
